### ISSUE TITLE
`d3-join` does too much

### ISSUE THREAD

**Issue by taras** [LocusEnergy/ember-d3-helpers#12]
`d3-join` accepts too many arguments. Handing `enter`, `update`, `exit` is enough. It doesn't need to also do selection and set data. I propose that we add a `d3-data` helper and use `d3-select-all` helper. 

Instead of this:

```hbs
{{shhh (compute (pipe
    (d3-select "svg")
    (d3-join "rect" data
      enter=(pipe
        (d3-append "rect")
        (d3-text (r/param))
      )
      update=(pipe
        (d3-text (r/param))
      )
      exit=(pipe
        (d3-remove)
      )
    )
  ))
}}
```

we would do this

```hbs
{{shhh (compute (pipe
    (d3-select "svg")
    (d3-select-all "rect")
    (d3-data data)
    (d3-join
      enter=(pipe
        (d3-append "rect")
        (d3-text (r/param))
      )
      update=(pipe
        (d3-text (r/param))
      )
      exit=(pipe
        (d3-remove)
      )
    )
  ))
}}
```

This would make it easier to follow examples and it make it more composable.

What do you think?

/cc @zigahertz @spencer516 @ivanvanderbyl

**Comment by zigahertz** [comment]
yeah, it's more explicit - I like this

**Comment by zigahertz** [comment]
closed by https://github.com/LocusEnergy/ember-d3-helpers/pull/13
