### ISSUE TITLE
demo link is broken

### ISSUE THREAD

**Issue by BryanCrotaz** [LocusEnergy/ember-d3-helpers#14]

**Comment by taras** [comment]
Oh yeah, need to remove that for now. There isn't much to demo in this library. It's a collection of primitives that can be used to build a graph. To see it in action, go to http://github.com/LocusEnergy/ember-sparkles

**Comment by BryanCrotaz** [comment]
Can you just change the link rather than removing?

Bryan

**Comment by zigahertz** [comment]
@bryan - yeah this is on my list, we do have a basic demo, I just need to setup the Github page, I will try to get to that this week

**Comment by zigahertz** [comment]
ok, the demo site now works
