### ISSUE TITLE
Please try ember-cli-d3-shape@0.9.4-4.1.1.0

### ISSUE THREAD

**Issue by ivanvanderbyl** [LocusEnergy/ember-d3-helpers#9]
Hi guys, I've updated `ember-cli-d3-shape` to require `D3` v4 directly, and will soon cut releases which are lock versioned with `d3@4.x`. I've released a pre-release of this as it makes a lot of assumptions about the require mechanism, and will soon possibly support using `d3` as a `peerDependency` so you can specify any version you like.

Please give it a try in this add-on and your app, and let me know if it loads etc.

**Comment by ivanvanderbyl** [comment]
Also, I was thinking it would be fitting to rename this it to `ember-cli-d3-shim`, thoughts?

**Comment by zigahertz** [comment]
@ivanvanderbyl thanks - this works great! Also, the renaming makes sense to me.

**Comment by ivanvanderbyl** [comment]
Rad, I'll push ahead with this and cut a new release shortly.

**Comment by zigahertz** [comment]
great - also, I tested this with ember-sparkles, it works fine there - I'll wait to upgrade that lib until you cut the new release
